theme: jekyll-theme-cayman
title: Abello Enterprise Distribution
exclude: [defaults, builds]
kramdown:
  parse_block_html: true
collections:
  apps:
    output: true
    permalink: /:collection/:name/index.html
